FROM node:14.17 as builder
WORKDIR /usr/src/frontend
COPY ["package.json", "package-lock.json", "./"]
RUN npm ci
COPY . .
RUN npm run build

FROM nginx:1.20.1-alpine
RUN apk add --no-cache bash
COPY --from=builder /usr/src/frontend/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/
# COPY resume.pdf /var/www/documents/
EXPOSE 89
CMD ["nginx", "-g", "daemon off;"]