AWSTemplateFormatVersion: 2010-09-09

Parameters:
  StackName:
    Type: String
    Default: my-site
    Description: The name of the parent Fargate networking stack that you       created. Necessary to locate and reference resources created by that stack.

  VpcId:
    Type: AWS::EC2::VPC::Id
    Default: vpc-d707deaa
  SubnetId1:
    Type: AWS::EC2::Subnet::Id
    Default: subnet-6819940e
  SubnetId2:
    Type: AWS::EC2::Subnet::Id
    Default: subnet-ca306c87

  Certificate:
    Type: String
    Default: arn:aws:acm:us-east-1:708746137251:certificate/591365e6-d7e5-456d-97df-ada13d481bc9

  Repository:
    Type: String
    Default: my-site
  Branch:
    Type: String
    Default: main
    Description: 'e.g. main or master'

  ServiceName:
    Type: String
    Default: my-site-backend
  ImageURL:
    Type: String
    Default: '708746137251.dkr.ecr.us-east-1.amazonaws.com/my-site-backend'
    Description: The URL of a Docker image that contains the application process that will handle the traffic for this service
  ContainerName:
    Type: String
    Default: my-site-backend
  ContainerPort:
    Type: Number
    Default: 80
    Description: The port number that the application inside the Docker container is binding to
  ContainerCPU:
    Type: Number
    Default: 256
    Description: How many CPU to assign to the container (1024 = 1 CPU)
  ContainerMemory:
    Type: Number
    Default: 512
    Description: How many MB of memory to assign to the container
  DesiredCount:
    Type: Number
    Default: 1
    Description: The number of copies of the service task to run

  Domain:
    Type: String
    Default: brendandagys.com
  SubDomain:
    Type: String
    Default: api

Resources:
  CodePipeline:
    Type: 'AWS::CodePipeline::Pipeline'
    Properties:
      ArtifactStore:
        Location: !Ref PipelineBucket
        Type: S3
      RoleArn: !GetAtt CodePipeLineRole.Arn
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeCommit
                Version: 1
              OutputArtifacts:
                - Name: MyAppCode
              Configuration:
                RepositoryName: !Ref Repository
                BranchName: !Ref Branch
              RunOrder: 2
        - Name: Approval
          Actions:
            - Name: ApprovalAction
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Provider: Manual
                Version: 1
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: BuildAction
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              InputArtifacts:
                - Name: MyAppCode
              OutputArtifacts:
                - Name: MyAppBuild
              Configuration:
                ProjectName: !Ref CodeBuild
              RunOrder: 3

  CodePipeLineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - 'codepipeline.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'codecommit:UploadArchive'
                  - 'codecommit:GetCommit'
                  - 'codecommit:GetUploadArchiveStatus'
                  - 'codecommit:GetBranch'
                  - 'codecommit:CancelUploadArchive'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 'codebuild:BatchGetBuilds'
                  - 'codebuild:StartBuild'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 's3:GetObject'
                  - 's3:GetObjectVersion'
                  - 's3:GetBucketVersioning'
                  - 's3:PutObject'
                Resource:
                  - !GetAtt PipelineBucket.Arn
                  - !Join ['', [!GetAtt PipelineBucket.Arn, '/*']]

  CodeBuild:
    Type: 'AWS::CodeBuild::Project'
    Properties:
      Name: !Sub ${AWS::StackName}-CodeBuild
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Type: LINUX_CONTAINER
        Image: 'aws/codebuild/standard:4.0'
      Source:
        Type: CODEPIPELINE
        BuildSpec: !Sub |
          version: 0.2
          phases:
            install:
              commands:
                - cd frontend
                - npm install
            build:
              commands:
                - npm run build
                - echo $CODEBUILD_SRC_DIR
            post_build:
              on-failure: CONTINUE
              commands:
                - aws s3 cp --recursive --acl public-read ./build s3://${DeployBucket}/
                #uncomment if you have service-worker.js 
                
                - aws s3 cp --acl public-read --cache-control="max-age=0, no-cache, no-store, must-revalidate" ./build/index.html s3://${DeployBucket}/
                
                - aws cloudfront create-invalidation --distribution-id ${Distribution} --paths "/*"
                
          artifacts:
            files:
              - 'frontend/build/**/*'

  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - 'codebuild.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      Path: /service-role/
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 's3:GetObject'
                  - 's3:GetObjectVersion'
                  - 's3:GetBucketVersioning'
                  - 's3:PutObject'
                Resource:
                  - !GetAtt PipelineBucket.Arn
                  - !Join ['', [!GetAtt PipelineBucket.Arn, '/*']]
              - Effect: Allow
                Action:
                  - 's3:GetObject'
                  - 's3:GetObjectVersion'
                  - 's3:GetBucketVersioning'
                  - 's3:PutObject'
                  - 's3:PutObjectAcl'
                Resource:
                  - !GetAtt DeployBucket.Arn
                  - !Join ['', [!GetAtt DeployBucket.Arn, '/*']]
              - Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                  - 'cloudfront:CreateInvalidation'
                Resource:
                  - '*'

  PipelineBucket:
    Type: 'AWS::S3::Bucket'

  DeployBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: PublicRead
      BucketName: 'brendandagys.com'
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html

  DeployBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref DeployBucket
      PolicyDocument:
        Id: MySiteBucketPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref DeployBucket
                - /*

  Distribution:
    Type: 'AWS::CloudFront::Distribution'
    DependsOn:
      - DistributionLogsBucket
    Properties:
      DistributionConfig:
        Comment: Connects to an S3 Bucket that hosts a React single-page-application
        Aliases:
          - brendandagys.com
          - www.brendandagys.com
        HttpVersion: http2
        IPV6Enabled: false
        ViewerCertificate:
          AcmCertificateArn: !Ref Certificate
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        PriceClass: PriceClass_100
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 10
        Origins:
          - DomainName: !GetAtt DeployBucket.DomainName
            Id: !Ref DeployBucket
            # OriginCustomHeaders:
            #   - HeaderName: Referer
            #     HeaderValue: origin-only
            CustomOriginConfig:
              OriginProtocolPolicy: http-only
        DefaultRootObject: index.html
        Enabled: true
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          TargetOriginId: !Ref DeployBucket
          ViewerProtocolPolicy: 'redirect-to-https'
        Logging:
          Bucket: my-site-cloudfront-distribution-logs.s3.amazonaws.com
          IncludeCookies: true

  DistributionLogsBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: 'my-site-cloudfront-distribution-logs'

  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: my-site

  FargateService:
    Type: AWS::ECS::Service
    DependsOn:
      - ListenerHTTPS
      - ListenerHTTP
    Properties:
      ServiceName: !Ref ServiceName
      Cluster: !Ref ECSCluster
      TaskDefinition: !Ref FargateServiceTaskDefinition
      LaunchType: FARGATE
      DesiredCount: !Ref DesiredCount
      LoadBalancers:
        - ContainerName: !Ref ContainerName
          ContainerPort: !Ref ContainerPort
          TargetGroupArn: !Ref FargateServiceLoadBalancerTargetGroup
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !Ref SubnetId1
          SecurityGroups:
            - !Ref FargateServiceSecurityGroup
      EnableECSManagedTags: true

  FargateServiceTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: my-site-backend
      NetworkMode: awsvpc
      Cpu: !Ref ContainerCPU
      Memory: !Ref ContainerMemory
      ExecutionRoleArn: 'arn:aws:iam::708746137251:role/ecsTaskExecutionRole'
      ContainerDefinitions:
        - Image: !Ref ImageURL
          Name: !Ref ContainerName
          PortMappings:
            - Protocol: tcp
              ContainerPort: !Ref ContainerPort
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: !Ref AWS::Region
              awslogs-group: !Ref FargateTaskDefinitionLogGroup
              awslogs-stream-prefix: ecs
          Environment:
            - Name: NODE_ENV
              Value: production

  FargateTaskDefinitionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: '/ecs/my-site-backend-task-definition'

  FargateServiceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Fargate Service Security Group
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !Ref FargateServiceLoadBalancerSecurityGroup
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 0
          ToPort: 65535
          CidrIp: 0.0.0.0/0
          # DestinationSecurityGroupId: '!Ref FargateServiceLoadBalancerSecurityGroup'

  FargateServiceLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: my-site-backend-ALB
      Scheme: internet-facing
      SecurityGroups:
        - !Ref FargateServiceLoadBalancerSecurityGroup
      Subnets:
        - !Ref SubnetId1
        - !Ref SubnetId2
      Type: application
      IpAddressType: ipv4

  FargateServiceLoadBalancerTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: my-site-backend-target-group
      Protocol: HTTP
      Port: !Ref ContainerPort
      TargetType: ip
      VpcId: !Ref VpcId
      HealthCheckEnabled: true
      HealthCheckPath: '/health'

  FargateServiceLoadBalancerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Fargate Service ALB Security Group
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  ListenerHTTPS:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - TargetGroupArn: !Ref FargateServiceLoadBalancerTargetGroup
          Type: forward
      LoadBalancerArn: !Ref FargateServiceLoadBalancer
      Protocol: HTTPS
      Port: 443
      Certificates:
        - CertificateArn: !Ref Certificate

  ListenerHTTP:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: redirect
          RedirectConfig:
            Protocol: HTTPS
            Port: 443
            Host: '#{host}'
            Path: '/#{path}'
            Query: '#{query}'
            StatusCode: 'HTTP_301'
      LoadBalancerArn: !Ref FargateServiceLoadBalancer
      Protocol: HTTP
      Port: 80

  DNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: Z1048063LC3J2IKH5GGI
      Name: !Ref Domain
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2
        DNSName: !GetAtt Distribution.DomainName

  DNSRecordAPI:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: Z1048063LC3J2IKH5GGI
      Name: !Join ['', [!Ref SubDomain, ., !Ref Domain]]
      Type: A
      AliasTarget:
        HostedZoneId: !GetAtt FargateServiceLoadBalancer.CanonicalHostedZoneID
        DNSName: !GetAtt FargateServiceLoadBalancer.DNSName
