version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    environment:
      EXPRESS_HOST: backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
