version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
    environment:
      EXPRESS_HOST: backend

  backend:
    build:
      context: ./backend
    ports:
      - '5001:5001'
    environment:
      PORT: 5001
