services:
  frontend:
    build:
      dockerfile: ./Dockerfile.prod
    ports:
      - '8080:8080'
    environment:
      NODE_ENV: production

  backend:
    environment:
      NODE_ENV: production
