services:
  frontend:
    build:
      dockerfile: ./Dockerfile.prod
    environment:
      NODE_ENV: production

  backend:
    build:
      dockerfile: ./Dockerfile.prod
    environment:
      NODE_ENV: production
