AWSTemplateFormatVersion: 2010-09-09

Parameters:
  HostedZoneId:
    Type: String
    Default: Z1048063LC3J2IKH5GGI

  Domain:
    Type: String
    Default: <REPLACE>.brendandagys.com
  DomainWWW:
    Type: String
    Default: www.<REPLACE>.brendandagys.com

  DistributionHomePage:
    Type: String
    Default: /

Resources:
  DNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref Domain
      Type: A
      AliasTarget:
        HostedZoneId:
          !ImportValue {
            !Sub: '${MasterStackName}-fargate-service-load-balancer-hosted-zone-id',
          }
        DNSName:
          !ImportValue {
            !Sub: '${MasterStackName}-fargate-service-load-balancer-dns-name',
          }

  DNSRecordWWW:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref DomainWWW
      Type: A
      AliasTarget:
        HostedZoneId:
          !ImportValue {
            !Sub: '${MasterStackName}-fargate-service-load-balancer-hosted-zone-id',
          }
        DNSName:
          !ImportValue {
            !Sub: '${MasterStackName}-fargate-service-load-balancer-dns-name',
          }
