AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Domain:
    Type: String
    Default: <REPLACE>.brendandagys.com
  DomainWWW:
    Type: String
    Default: www.<REPLACE>.brendandagys.com
  HostedZoneId:
    Type: String
    Default: Z1048063LC3J2IKH5GGI

  DistributionHomePage:
    Type: String
    Default: /

Resources:
  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: !Sub 'Origin: API Fargate container for ${AWS::StackName}'
        Aliases:
          - !Ref Domain
          - !Ref DomainWWW
        Origins:
          - Id: !ImportValue my-site-Fargate-service
            DomainName: !ImportValue my-site-Fargate-service-load-balancer-DNS-name
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
              OriginSSLProtocols:
                - TLSv1.2
        ViewerCertificate:
          AcmCertificateArn: !ImportValue my-site-certificate
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        CustomErrorResponses:
          # - ErrorCode: 403
          #   ResponseCode: 200
          #   ResponsePagePath: !Ref DistributionHomePage
          #   ErrorCachingMinTTL: 10
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: !Ref DistributionHomePage
            ErrorCachingMinTTL: 10
        DefaultRootObject: !Ref DistributionHomePage
        PriceClass: PriceClass_100
        HttpVersion: http2
        IPV6Enabled: false
        DefaultCacheBehavior:
          TargetOriginId: !ImportValue my-site-Fargate-service
          ViewerProtocolPolicy: redirect-to-https
          CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
          OriginRequestPolicyId: 216adef6-5c7f-47e4-b989-5492eafa07d3
          Compress: true
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
            - POST
            - PUT
            - PATCH
            - DELETE
          CachedMethods:
            - GET
            - HEAD
          FunctionAssociations:
            # - EventType: viewer-request
            #   FunctionARN: !ImportValue my-site-CloudFront-function-canonical-URL
            - EventType: viewer-response
              FunctionARN: !ImportValue my-site-CloudFront-function-security-headers
        # CacheBehaviors:
        #   - PathPattern: api/*
        #     TargetOriginId: !ImportValue my-site-Fargate-service
        #     ViewerProtocolPolicy: redirect-to-https
        #     CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
        #     OriginRequestPolicyId: 216adef6-5c7f-47e4-b989-5492eafa07d3
        #     Compress: true
        #     AllowedMethods:
        #       - GET
        #       - HEAD
        #       - OPTIONS
        #       - POST
        #       - PUT
        #       - PATCH
        #       - DELETE
        #     CachedMethods:
        #       - GET
        #       - HEAD
        #     FunctionAssociations:
        #       - EventType: viewer-response
        #         FunctionARN: !ImportValue my-site-CloudFront-function-security-headers
        Logging:
          Bucket: my-site-cloudfront-distribution-logs.s3.amazonaws.com
          IncludeCookies: true
          Prefix: !Sub '${AWS::StackName}-logs'

  OriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub
          - '${Domain} OAI'
          - { Domain: !Ref Domain }

  DNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref Domain
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2
        DNSName: !GetAtt Distribution.DomainName

  DNSRecordWWW:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref DomainWWW
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2
        DNSName: !GetAtt Distribution.DomainName
